Adds alert report command
giantswarm/oncall-scheduler pull request #2
Opened 2019-06-26 16:31 UTC by JosephSalisbury

2019-06-26 18:37 UTC, xh3b4sd requested changes
The PR contains too many changes and should be broken down.

2019-06-26 18:37 UTC, xh3b4sd commented on cmd/report/alert/runner.go
> +	if err := slack.PostAlertSummary(summary); err != nil {
```suggestion
	err = slack.PostAlertSummary(summary)
	if err != nil {
```

2019-06-26 18:37 UTC, xh3b4sd commented on pkg/opsgenieclient/client_alert.go
> +	req, err := http.NewRequest(http.MethodGet, "https://api.opsgenie.com/v2/alerts/count", nil)
Having a constant that is visible in godoc would be cool.

2019-06-26 18:37 UTC, xh3b4sd commented on pkg/opsgenieclient/client_alert.go
> +func (c *Client) getUnixTime(dayShift int) int64 {
These deserve unit tests.

2019-06-26 18:37 UTC, xh3b4sd commented on pkg/slackclient/client_summary.go
> +	); err != nil {
Please don't mix that if possible. It makes reading code way harder.

2019-06-26 20:22 UTC, JosephSalisbury commented
ptalaaaaaaaaaaaaaaa

2019-06-27 09:04 UTC, JosephSalisbury commented
Splittin'

2019-06-27 09:37 UTC, closed without merging